version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: raw data gw data for investigation
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales data of products
      - name: product
        identifier: raw_gz_product
        description: product list
      - name: ship
        identifier: raw_gz_ship
        description: shipping data of products


