version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / we have one row per product_id found in each orders_id.
        columns:
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: order id number
          - name: products_id
            description: product id number
          - name: revenue
            description: revenue of each product
          - name: quantity
            description: quantity of items ordered for each product
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
      - name: product
        identifier: raw_gz_product
        description: product of greenweez
        columns:
          - name: products_id
            description: Primary key of the table
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: purchase price of each product

      - name: ship
        identifier: raw_gz_ship
        description: shipping data of greenweez products
        columns:
          - name: orders_id
            description: Primary key of the table
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: shipping fee charged
          - name: logcost
            description: logestics cost
          - name: ship_cost
            description: shipping cost
          


